# Generated by Django 4.0.6 on 2022-07-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tour_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField()),
                ('month', models.TextField()),
                ('sigoon', models.CharField(max_length=10)),
                ('sigoon_vcnt', models.BigIntegerField()),
                ('sns_cnt', models.BigIntegerField()),
                ('spend_type', models.CharField(max_length=10)),
                ('spend_amount', models.BigIntegerField()),
                ('depart_from', models.CharField(max_length=10)),
                ('core_area', models.IntegerField()),
                ('male_ratio', models.FloatField()),
                ('age_10s_under', models.FloatField()),
                ('age_20s', models.FloatField()),
                ('age_30s', models.FloatField()),
                ('age_40s', models.FloatField()),
                ('age_50s', models.FloatField()),
                ('age_60s', models.FloatField()),
                ('age_70s_over', models.FloatField()),
                ('do_cnt', models.BigIntegerField()),
                ('rel_crowded', models.FloatField()),
            ],
            options={
                'db_table': 'tour_data',
                'managed': False,
            },
        ),
    ]
